# NumPy Opdrachten

In dit notebook vind je de volgende opdrachten:


- <a href="#np_opdracht1"> Opdracht 1</a> Maak deze opdracht ter voorbereiding op het college over NumPy.
- <a href="#np_opdracht2"> Opdracht 2</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht3"> Opdracht 3</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht4"> Opdracht 4</a> Deze opdracht is facultatief, voor als je meer uitdaging wilt.

<a id="np_opdracht1"></a>
## Opdracht 1 
**Maak deze opdracht ter voorbereiding op het college**

In [138]:
import numpy

- Maak een 1D array x aan met de cijfers 0 t/m 5

In [139]:
# Een één-dimensionale array met de getallen 0 tot en met 5:
    
x = numpy.array([0,1,2,3,4,5])
x

array([0, 1, 2, 3, 4, 5])

In [140]:
# Of zo: 
x2 = numpy.arange(6)
x2

array([0, 1, 2, 3, 4, 5])

- Laat de vorm (grootte van de dimensies) van de array zien

In [141]:
print("De dimensie van x is {}.".format(x.shape))
print("De dimensie van x2 is {}.".format(x2.shape))

De dimensie van x is (6,).
De dimensie van x2 is (6,).


- Hervorm de array x tot een 2D array (2, 3) 

In [142]:
x = numpy.reshape(x, (2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [143]:
# Of laat _NumPy_ de grootte van de tweede dimensie zelf bepalen:
x2 = numpy.reshape(x2, (2,-1))
x2

array([[0, 1, 2],
       [3, 4, 5]])

- Wat is nu de vorm?


In [144]:
print("De dimensie van x is {}.".format(x.shape))
print("De dimensie van x2 is {}.".format(x2.shape))

De dimensie van x is (2, 3).
De dimensie van x2 is (2, 3).


- Laat het datatype zien


In [145]:
print("Het datatype van x is {}.".format(x.dtype))
print("Het datatype van x2 is {}.".format(x2.dtype))

Het datatype van x is int32.
Het datatype van x2 is int32.


- Sla een kopie van de array op in y


In [146]:
y = x.copy()
y

array([[0, 1, 2],
       [3, 4, 5]])

In [147]:
# **Let op!** `x = y` maakt geen kopie, maar kopieert alleen de _referentie_ naar hetzelfde object. 
# Met andere woorden, `x` en `y` zijn vanaf dat moment twee namen voor _dezelfde_ array:

y2 = x2
x2[0,0] = 99
print("x2 =\n {}\n".format(x2))
print("y2 =\n {}".format(y2))

x2 =
 [[99  1  2]
 [ 3  4  5]]

y2 =
 [[99  1  2]
 [ 3  4  5]]


In [148]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [149]:
x[0,0] = 99

In [150]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [151]:
x

array([[99,  1,  2],
       [ 3,  4,  5]])

- Maak een transpose van x



In [152]:
x = numpy.transpose(x)
x

array([[99,  3],
       [ 1,  4],
       [ 2,  5]])

- Maak een transpose van y


In [153]:
y = y.T
y

array([[0, 3],
       [1, 4],
       [2, 5]])

- Vermenigvuldig alle waarden van y met 2


In [154]:
y = 2 * y
y

array([[ 0,  6],
       [ 2,  8],
       [ 4, 10]])

- Concateneer de twee arrays in een nieuwe array `z`


In [155]:
z = numpy.vstack((x,y))
z1 = numpy.concatenate((x,y),axis=1)
z2 = numpy.c_[x,y]

print("z =\n {}\n".format(z))
print("z1 =\n {}\n".format(z1))
print("z2 =\n {}".format(z2))

z =
 [[99  3]
 [ 1  4]
 [ 2  5]
 [ 0  6]
 [ 2  8]
 [ 4 10]]

z1 =
 [[99  3  0  6]
 [ 1  4  2  8]
 [ 2  5  4 10]]

z2 =
 [[99  3  0  6]
 [ 1  4  2  8]
 [ 2  5  4 10]]


- Geef het gemiddelde, modus, mediaan en de standaarddeviatie van z


In [156]:
print("Gemiddelde van z is: {}".format(z.mean()))
print("Standaarddeviatie van z is: {:0.4f}\n".format(numpy.std(z)))
print("Gemiddelde van z1 is: {}".format(z1.mean()))
print("Standaarddeviatie van z1 is: {:0.4f}".format(numpy.std(z1)))      

Gemiddelde van z is: 12.0
Standaarddeviatie van z is: 26.3755

Gemiddelde van z1 is: 12.0
Standaarddeviatie van z1 is: 26.3755


<a id="np_opdracht2"></a>
## Opdracht 2
**Python list vs. NumPy**

- Maak een list `lst` met 1.000.001 willekeurige getallen tussen 0 en 10 (gebruik `random.randint(0, 10)`)
- Bepaal de mediaan
- Maak een list met daarin het kwadraat van elk element in `lst`
- Maak een list met daarin alleen alle even getallen uit `lst`
- Maak een tweede list `lst2` met 1.000.001 willekeurige getallen
- Maak een list met daarin de som van de elementen uit `lst` en `lst2`, dus:
  - `lst_samen[0] = lst[0] + lst2[0]`,
  - `lst_samen[1] = lst[1] + lst2[1]`,
  - etc.

- Doe bovenstaande ook met Numpy

- Gebruik `%timeit` voor je code om de snelheid te vergelijken

In [157]:
import math
import random
import numpy as np

In [158]:
lst = [random.randint(0, 10) for i in range(10**6+1)]
len(lst)

1000001

In [159]:
max(lst)

10

In [160]:
min(lst)

0

In [161]:
array = np.random.randint(0, 11, size=10**6+1)
array.shape

(1000001,)

In [162]:
array.max()

10

In [163]:
array.min()

0

In [164]:
%timeit lst = [random.randint(1, 10) for i in range(10**6+1)]

599 ms ± 40.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [165]:
%timeit array = np.random.randint(1, 10, size=10**6+1)

17 ms ± 560 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [166]:
sum(lst)

4997434

In [167]:
array.sum()

5003796

In [168]:
%timeit sum(lst)

6.15 ms ± 490 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [169]:
%timeit array.sum()

214 µs ± 25.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [170]:
sorted(lst)[len(lst)//2]

5

In [171]:
np.median(array)

5.0

In [172]:
# %timeit sorted(lst)[len(lst)//2]

In [173]:
%timeit (np.median(array))

8 ms ± 460 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [174]:
lst_kwadraat = [x**2 for x in lst]

In [175]:
max(lst_kwadraat)

100

In [176]:
array10 = array**2

In [177]:
array10.max()

100

In [178]:
%timeit [x**2 for x in lst]

182 ms ± 2.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [179]:
# %timeit array**2

In [180]:
lst_even = [x for x in lst if x % 2 == 0]

In [181]:
len(lst_even)

546613

In [182]:
lst_even2 = list(filter(lambda x: x % 2 == 0, lst))

In [183]:
len(lst_even2)

546613

In [184]:
%timeit [x for x in lst if x % 2 == 0]

41.9 ms ± 3.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [185]:
%timeit list(filter(lambda x: x % 2 == 0, lst))

72.6 ms ± 6.56 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [186]:
array_even = array[array % 2 == 0]

In [187]:
len(array_even)

545663

In [188]:
%timeit array[array % 2 == 0]

8.48 ms ± 465 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [189]:
lst2 = [random.randint(0, 10) for i in range(len(lst))]
len(lst2)

1000001

In [190]:
array2 = np.random.randint(0, 11, size=len(array))
array2.shape

(1000001,)

In [191]:
lst_samen = [ lst[i] + lst2[i] for i in range(len(lst)) ]
max(lst_samen)

20

In [192]:
array_samen = array + array2
array_samen.max()

20

In [193]:
%timeit [ lst[i] + lst2[i] for i in range(len(lst)) ]

69.7 ms ± 4.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [194]:
%timeit array + array2

1.5 ms ± 144 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


<a id="np_opdracht3"></a>
## Opdracht 3

De blokcoördinator D.O. Cent van blok A  wil graag de cijfers analyseren en verwerken. Het blok bestaat uit 3 vakken, die door 10 studenten gevolgd zijn. Analyse omvat o.a. het bepalen van gemiddelde cijfer, het aantal voldoendes en cursusrendement. De verwerking bestaat uit het corrigeren van de cijfers.

In `blokAcijfers.txt` staan de cijfers per vak (naast elkaar staan de vakken, onder elkaar de studenten):

vak1 | vak2 | vak3
----|-------|------
6.5 | 7.3   | 6.4
8.0 | 8.0	| 8.5
3.2	| 4.0	| 5.0
7.9	| 7.1	| 3.5
7.3	| 7.8	| 8.0
8.6	| 8.0	| 9.0
4.0	| 6.0	| 5.5
7.3	| 7.8	| 7.8
4.5	| 5.6	| 7.7
5.0	| 7.0	| 7.2


In [195]:
import numpy as np

-	Lees tekstbestand: blokAcijfers.txt in, in een numpy array met naam `cijfers`.
-	Laat zien dat de gegevens goed ingelezen zijn.
-	Toon de array attributen.

In [196]:
vCijfers = np.loadtxt("blokAcijfers.txt")

print("Cijfers:\n{}\n".format(vCijfers))

print("Cijfers heeft {} elementen, {} dimensies, de vorm {} en de inhoud is van type {}.\n".format(vCijfers.size, vCijfers.ndim, vCijfers.shape, vCijfers.dtype))

Cijfers:
[[6.5 7.3 6.4]
 [8.  8.  8.5]
 [3.2 4.  5. ]
 [7.9 7.1 3.5]
 [7.3 7.8 8. ]
 [8.6 8.  9. ]
 [4.  6.  5.5]
 [7.3 7.8 7.8]
 [4.5 5.6 7.7]
 [5.  7.  7.2]]

Cijfers heeft 30 elementen, 2 dimensies, de vorm (10, 3) en de inhoud is van type float64.



De docent ziet dat er 2 cijfers fout zijn en wil deze corrigeren
-	Wijzig de volgende cijfers:
    *	vak-2, student-3  cijfer 4.0 moet 4.3 worden.
    *	vak-1, student-10, cijfer 5.0 moet 4.8 worden.

In [197]:
vCijfers[2,1] = 4.3
vCijfers[9,0] = 4.8

print("Verbeterde cijfers:\n{}\n".format(vCijfers))

Verbeterde cijfers:
[[6.5 7.3 6.4]
 [8.  8.  8.5]
 [3.2 4.3 5. ]
 [7.9 7.1 3.5]
 [7.3 7.8 8. ]
 [8.6 8.  9. ]
 [4.  6.  5.5]
 [7.3 7.8 7.8]
 [4.5 5.6 7.7]
 [4.8 7.  7.2]]



De docent wil wat basisgegevens weten.
-	Bepaal minimum, maximum en gemiddelde van alle cijfers.
-	Bepaal minimum, maximum en gemiddelde van elk vak (3 getallen).
-	Bepaal minimum, maximum en gemiddelde van elke student (10 getallen).

In [198]:
print("Van het totaal is het minimum {}, het maximum {} en het gemiddelde {:0.2f}.\n".format(vCijfers.min(), vCijfers.max(), vCijfers.mean()))
print("Van vak 1 is het minimum {}, het maximum {} en het gemiddelde {:0.2f}.".format(vCijfers[:,0].min(), vCijfers[:,0].max(), vCijfers[:,0].mean()))
print("Van vak 2 is het minimum {}, het maximum {} en het gemiddelde {:0.2f}.".format(vCijfers[:,1].min(), vCijfers[:,1].max(), vCijfers[:,1].mean()))
print("Van vak 3 is het minimum {}, het maximum {} en het gemiddelde {:0.2f}.\n".format(vCijfers[:,2].min(), vCijfers[:,2].max(), vCijfers[:,2].mean()))

Van het totaal is het minimum 3.2, het maximum 9.0 en het gemiddelde 6.65.

Van vak 1 is het minimum 3.2, het maximum 8.6 en het gemiddelde 6.21.
Van vak 2 is het minimum 4.3, het maximum 8.0 en het gemiddelde 6.89.
Van vak 3 is het minimum 3.5, het maximum 9.0 en het gemiddelde 6.86.



In [199]:
print("Minimum voor elke student:", np.min(vCijfers, axis=1))
print("Maximum voor elke student:", np.max(vCijfers, axis=1))
print("Gemiddelde voor elke student:", np.around(np.mean(vCijfers, axis=1), 1))

Minimum voor elke student: [6.4 8.  3.2 3.5 7.3 8.  4.  7.3 4.5 4.8]
Maximum voor elke student: [7.3 8.5 5.  7.9 8.  9.  6.  7.8 7.7 7.2]
Gemiddelde voor elke student: [6.7 8.2 4.2 6.2 7.7 8.5 5.2 7.6 5.9 6.3]


De docent wil graag zien wat de cijfers zijn als ze afgerond worden op hele getallen.
-	Kopieer de array naar een nieuwe array.
-	Rond de waarden af.
-	Laat de resultaten zien.

In [200]:
vCijfersRond = vCijfers.copy()
vCijfersRond = np.around(vCijfersRond, 0)

print("\nAfgeronde cijfers:\n{}\n".format(vCijfersRond))


Afgeronde cijfers:
[[6. 7. 6.]
 [8. 8. 8.]
 [3. 4. 5.]
 [8. 7. 4.]
 [7. 8. 8.]
 [9. 8. 9.]
 [4. 6. 6.]
 [7. 8. 8.]
 [4. 6. 8.]
 [5. 7. 7.]]



Er is een fout gemaakt bij de cijfers van het 1e vak. Iedere student krijgt 0.5 punt extra erbij.
-	Vul een ‘ophoogarray’ bestaande uit 3 kolommen en elk 10 rijen en vul deze eerst met 0.0 en daarna de eerste rij met de waarden 0.5.
-	Tel de ophoogarray op bij de cijfer array.

In [201]:
vCijfersVerhoging = np.zeros_like(vCijfers)
vCijfersVerhoging[:, 0] = 0.5

vCijfersNaVerhoging = vCijfers + vCijfersVerhoging

print("\nCijfers na verhoging:\n{}\n".format(vCijfersNaVerhoging))


Cijfers na verhoging:
[[7.  7.3 6.4]
 [8.5 8.  8.5]
 [3.7 4.3 5. ]
 [8.4 7.1 3.5]
 [7.8 7.8 8. ]
 [9.1 8.  9. ]
 [4.5 6.  5.5]
 [7.8 7.8 7.8]
 [5.  5.6 7.7]
 [5.3 7.  7.2]]



De docent wil een lijstje waarin hij in één opslag ziet waar een voldoende (`True`) en waar een onvoldoende (`False`) staat.  
-	Maakt dit lijstje.

In [202]:
print(vCijfers >= 5.5)

[[ True  True  True]
 [ True  True  True]
 [False False False]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]]


<a id="np_opdracht4"></a>
## Opdracht 4
**Deze opdracht is facultatief**

In [203]:
import numpy as np

#### 3. Create a null vector of size 10

#### 6.  Create a null vector of size 10 but the fifth value which is 1

#### 8.  Reverse a vector with values ranging from 10 to 49 (first element becomes last)

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### 11. Create a 3x3 identity matrix

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

#### 15. Create a 2d array with 1 on the border and 0 inside

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

#### 29. How to round away from zero a float array ?

#### 30. How to find common values between two arrays?

#### 36. Extract the integer part of a random array using 5 different methods

In [204]:
Z = np.random.uniform(0,10,10)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

#### 40. Create a random vector of size 10 and sort it

#### 42. Consider two random array A and B, check if they are equal

#### 45. Create random vector of size 10 and replace the maximum value by 0

#### 50. How to find the closest value (to a given scalar) in a vector?

In [205]:
v = np.random.uniform(0,100)

#### 52. Consider a random vector with shape (10,2) representing coordinates, find point by point distances

In [206]:
Z = np.random.random((10,2))


#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

In [207]:
Z = np.random.uniform(0,1,10)
z = 0.5

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 72. How to swap two rows of an array?

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 83. How to find the most frequent value in an array?

#### 89. How to get the n largest values of an array